# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2020
customText = "å¥½æƒ³é¤Šè²“é˜¿~~"

[dateFormat]
published = "2006/01/02"
lastUpdated = "2006/01/02 15:04 Asia/Taipei"

[sidebar]
emoji = "ğŸ’¤"
subtitle = "æˆå¤§ç‰©ç†ç³»å¤§ä¸‰"

[sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

[article]
math = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

# [widgets.homepage.params]
# limit = 10

# [[widgets.homepage]]
# type = "categories"

[widgets.homepage.params]
limit = 100

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 20

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "simbafs"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "dark"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "gitalk"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = "simbafs"
admin = "simbafs"
repo = "blog"
clientID = "<< gitalk.clientID >>"
clientSecret = "<< gitalk.clientSecret >>"
language = "zh-TW"

[comments.cusdis]
host = ""
id = ""
